install.packages('RSQLite')
library('RSQLite')
data("mtcars")
mtcars$car_names<-rownames(mtcars)
rownames(mtcars)<-c()
head(mtcars)
conn <- dbConnect(RSQLite::SQLite(), "CarsDB.db")
dbWriteTable(conn, "cars_data", mtcars)
dbListTables(conn)
dbListFields(conn, "cars_data")
rdd<- dbReadTable(conn,"cars_data")
